### ISSUE TITLE
E-Mail Notification label not display properly

### ISSUE THREAD

**Issue by VarunAgw** [SupportFlow/supportflow#97]
Branch: Notifications

In `wp-admin/post-new.php?post_type=sf_thread` in details meta box "E-Mail Notifications" label is not shown properly.

I found it is cause by this CSS property in css/admin.css

``` css
#supportflow-details #misc-publishing-actions label {
    width:   50px;
    display: inline-block;
}
```

I am not sure why it is there. Should I remove it?
